name: test_codeunion
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  injectable: ^2.3.2
  google_fonts: ^6.1.0
  bloc: ^8.1.2
dev_dependencies:
  auto_route_generator: ^7.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
